import {useCallback,useEffect,useRef,useState} from "react";
import {commands,savedSyncs,savedSyncAction,onSyncLibraryChanged,onKaraokeReady,type SavedSync} from "./lib/backend";
import type {NowPlaying} from "./types";

function Glyph({kind}:{kind:"close"|"refresh"|"delete"|"music"}){
 return <svg width="14" height="14" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{kind==="close"?<path d="m4 4 8 8M12 4l-8 8"/>:kind==="refresh"?<><path d="M12.3 5A5 5 0 1 0 13 9M12.3 2v3.5H8.8"/></>:kind==="delete"?<><path d="M3 4.5h10M6 2.5h4M4.5 4.5l.5 9h6l.5-9M6.5 7v4M9.5 7v4"/></>:<><path d="M10.5 10V3l-5 1v7"/><ellipse cx="4" cy="11.5" rx="1.5" ry="1"/><ellipse cx="9" cy="10.5" rx="1.5" ry="1"/></>}</svg>;
}
function Cover({song}:{song:SavedSync}){const [src,setSrc]=useState<string|null>(null);useEffect(()=>{let live=true;setSrc(null);if(song.thumb_key)void commands.historyThumbUrl(song.thumb_key).then(s=>{if(live)setSrc(s);}).catch(()=>{});return ()=>{live=false;};},[song.thumb_key]);return <div className="grid h-10 w-10 shrink-0 place-items-center overflow-hidden rounded bg-fg/5 text-muted">{src?<img src={src} alt="" className="h-full w-full object-cover" onError={()=>setSrc(null)}/>:<Glyph kind="music"/>}</div>;}
export function SavedSyncs({np,onClose}:{np:NowPlaying;onClose:(restoreFocus?:boolean)=>void}){
 const [rows,setRows]=useState<SavedSync[]|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState<string|null>(null),[notice,setNotice]=useState("");
 const [undo,setUndo]=useState<{key:string;revision:number}|null>(null);const alive=useRef(true),serial=useRef(0),panel=useRef<HTMLDivElement>(null);
 const refresh=useCallback(async()=>{const n=++serial.current;try{const data=await savedSyncs();if(alive.current&&n===serial.current){setRows(data);setError("");}}catch{if(alive.current&&n===serial.current)setError("Couldn’t load saved syncs.");}},[]);
 useEffect(()=>{alive.current=true;void refresh();const a=onSyncLibraryChanged(()=>void refresh()),b=onKaraokeReady(()=>void refresh());return ()=>{alive.current=false;serial.current++;a();b();};},[refresh]);
 useEffect(()=>{panel.current?.focus();const outside=(e:PointerEvent)=>{if(!panel.current?.parentElement?.contains(e.target as Node))onClose(false);};const escape=(e:KeyboardEvent)=>{if(e.key==="Escape"){e.preventDefault();e.stopPropagation();onClose();}};document.addEventListener("pointerdown",outside);document.addEventListener("keydown",escape,true);return ()=>{document.removeEventListener("pointerdown",outside);document.removeEventListener("keydown",escape,true);};},[onClose]);
 async function act(key:string,action:"refresh"|"delete"|"undo",revision?:number){if(busy)return;setBusy(key);setError("");try{const rev=await savedSyncAction(key,action,revision);if(!alive.current)return;if(action==="delete"){setUndo({key,revision:rev});setNotice("Timing deleted.");}else{setUndo(null);setNotice(action==="refresh"?"Will relearn on your next full listen. Current timing stays available.":"Timing restored.");}await refresh();}catch(e){if(alive.current)setError(typeof e==="string"?e:"Couldn’t update this sync.");}finally{if(alive.current)setBusy(null);}}
 const sorted=rows?[...rows].sort((a,b)=>Number(b.title===np.title&&b.artist===np.artist)-Number(a.title===np.title&&a.artist===np.artist)):[];
 const btn="grid h-7 w-7 shrink-0 place-items-center rounded text-muted hover:bg-fg/10 hover:text-fg focus-visible:outline focus-visible:outline-2 focus-visible:outline-fg/50 disabled:opacity-40";
 return <div ref={panel} role="dialog" aria-label="Saved syncs" tabIndex={-1} onMouseDown={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==="Escape"){e.stopPropagation();onClose();}}} className="absolute right-0 top-full z-50 mt-2 flex max-h-[min(320px,65vh)] w-[312px] max-w-[calc(100vw-32px)] flex-col overflow-hidden rounded-xl border border-border/15 bg-surface text-fg shadow-xl shadow-black/40 outline-none">
  <div className="flex shrink-0 items-center justify-between px-3 pb-2 pt-3"><div className="text-sm font-medium">Saved syncs <span className="ml-1 text-xs font-normal text-muted">{rows?.length??""}</span></div><button className={btn} aria-label="Close saved syncs" onClick={()=>onClose()}><Glyph kind="close"/></button></div>
  <div className="min-h-0 overflow-y-auto px-1 pb-2">{rows===null&&!error?<p className="px-3 py-7 text-xs text-muted">Loading saved timing…</p>:rows?.length===0?<div className="px-3 py-7"><p className="text-sm">Your collection starts here.</p><p className="mt-1 text-xs leading-5 text-muted">Listen to a song with lyrics from start to finish. Saved word timing will appear here.</p></div>:sorted.map(song=><div key={song.key} className="group/sync flex min-h-14 items-center gap-2.5 rounded-lg px-2 py-1.5 hover:bg-fg/5"><Cover song={song}/><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{song.title}</div><div className="truncate text-xs text-muted">{song.refresh?"Refresh on next listen":song.artist}</div></div><div className="flex shrink-0 opacity-0 group-hover/sync:opacity-100 focus-within:opacity-100"><button className={btn} disabled={!!busy} title="Relearn on next full listen" aria-label={`Refresh timing for ${song.title}`} onClick={()=>void act(song.key,"refresh")}><Glyph kind="refresh"/></button><button className={btn} disabled={!!busy} title="Delete timing" aria-label={`Delete timing for ${song.title}`} onClick={()=>void act(song.key,"delete")}><Glyph kind="delete"/></button></div></div>)}</div>
  {error&&<div role="alert" className="px-3 pb-3 text-xs text-muted">{error} <button className="underline" onClick={()=>void refresh()}>Retry</button></div>}
  {notice&&<div role="status" className="border-t border-border/10 px-3 py-2 text-xs leading-5 text-muted">{notice}{undo&&<button className="ml-2 text-fg underline" disabled={!!busy} onClick={()=>void act(undo.key,"undo",undo.revision)}>Undo</button>}</div>}
 </div>;
}
